-- Все объекты курсовой имеют префикс lf_. Внешние объекты не изменяются.
CREATE TABLE lf_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL UNIQUE CHECK (email=lower(email) AND email LIKE '%_@_%._%'),
    display_name varchar(80) NOT NULL CHECK (length(trim(display_name))>0),
    password_hash varchar(100) NOT NULL,
    state varchar(12) NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','verified','blocked')),
    email_confirmed_at timestamptz,
    token_version integer NOT NULL DEFAULT 0 CHECK (token_version>=0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (state<>'verified' OR email_confirmed_at IS NOT NULL)
);
COMMENT ON TABLE lf_users IS 'poteryashki.course.v1';
CREATE TABLE lf_roles (
    code varchar(16) PRIMARY KEY CHECK (code IN ('user','moderator','admin')),
    title varchar(80) NOT NULL
);
CREATE TABLE lf_user_roles (
    user_id bigint REFERENCES lf_users ON DELETE RESTRICT,
    role_code varchar(16) REFERENCES lf_roles ON DELETE RESTRICT,
    PRIMARY KEY (user_id,role_code)
);
CREATE TABLE lf_refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES lf_users,
    token_hash varchar(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (expires_at>created_at)
);
CREATE TABLE lf_verifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES lf_users,
    state varchar(12) NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','approved','rejected')),
    reviewer_id bigint REFERENCES lf_users,
    reason text,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    reviewed_at timestamptz,
    CHECK ((state='pending' AND reviewer_id IS NULL AND reviewed_at IS NULL) OR
           (state<>'pending' AND reviewer_id IS NOT NULL AND reviewed_at IS NOT NULL)),
    CHECK (reviewer_id IS NULL OR reviewer_id<>user_id),
    CHECK (state<>'rejected' OR (reason IS NOT NULL AND length(trim(reason))>0))
);
CREATE TABLE lf_verification_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES lf_users,
    purpose varchar(16) NOT NULL CHECK (purpose IN ('email_confirm','password_reset')),
    token_hash varchar(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (expires_at>created_at),
    CHECK (consumed_at IS NULL OR consumed_at>=created_at)
);
CREATE TABLE lf_tariffs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(80) NOT NULL,
    amount numeric(12,2) NOT NULL CHECK (amount>0),
    duration_days integer NOT NULL DEFAULT 30 CHECK (duration_days BETWEEN 1 AND 365),
    active boolean NOT NULL DEFAULT true
);
CREATE TABLE lf_payment_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES lf_users,
    tariff_id bigint NOT NULL REFERENCES lf_tariffs,
    request_key uuid NOT NULL UNIQUE,
    amount numeric(12,2) NOT NULL CHECK (amount>0),
    duration_days integer NOT NULL CHECK (duration_days BETWEEN 1 AND 365),
    currency char(3) NOT NULL DEFAULT 'RUB' CHECK (currency='RUB'),
    state varchar(12) NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','paid','cancelled')),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    paid_at timestamptz,
    CHECK ((state='paid')=(paid_at IS NOT NULL))
);
CREATE TABLE lf_payment_events (
    provider_event_id varchar(100) PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES lf_payment_orders,
    amount numeric(12,2) NOT NULL CHECK (amount>0),
    currency char(3) NOT NULL CHECK (currency='RUB'),
    received_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE lf_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES lf_users,
    payment_order_id bigint NOT NULL UNIQUE REFERENCES lf_payment_orders,
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    CHECK (ends_at>starts_at)
);
CREATE TABLE lf_organizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL UNIQUE,
    phone varchar(40) NOT NULL,
    address text,
    instructions text NOT NULL,
    source_url text NOT NULL CHECK (source_url LIKE 'https://%'),
    verified_on date NOT NULL
);
CREATE TABLE lf_locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city varchar(80) NOT NULL DEFAULT 'Санкт-Петербург',
    description varchar(240) NOT NULL,
    latitude numeric(9,6) CHECK (latitude BETWEEN -90 AND 90),
    longitude numeric(9,6) CHECK (longitude BETWEEN -180 AND 180),
    metro_station varchar(100),
    organization_id bigint REFERENCES lf_organizations,
    CHECK ((latitude IS NULL)=(longitude IS NULL))
);
CREATE TABLE lf_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(80) NOT NULL UNIQUE,
    auction_allowed boolean NOT NULL DEFAULT true
);
CREATE TABLE lf_listings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id bigint NOT NULL REFERENCES lf_users,
    category_id bigint NOT NULL REFERENCES lf_categories,
    location_id bigint NOT NULL REFERENCES lf_locations,
    kind varchar(5) NOT NULL CHECK (kind IN ('lost','found')),
    title varchar(120) NOT NULL CHECK (length(trim(title))>0),
    description text NOT NULL CHECK (length(trim(description))>0),
    event_at timestamptz NOT NULL,
    event_until timestamptz,
    state varchar(12) NOT NULL DEFAULT 'draft' CHECK
      (state IN ('draft','pending','published','reserved','returned','auctioned','archived','rejected')),
    custodian_org_id bigint REFERENCES lf_organizations,
    official_reported_at timestamptz,
    moderator_id bigint REFERENCES lf_users,
    moderated_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    search_vector tsvector GENERATED ALWAYS AS
      (to_tsvector('russian'::regconfig,coalesce(title,'')||' '||coalesce(description,''))) STORED,
    CHECK (official_reported_at IS NULL OR official_reported_at>=event_at),
    CHECK (event_until IS NULL OR (kind='lost' AND event_until>=event_at)),
    CHECK (kind='found' OR (custodian_org_id IS NULL AND official_reported_at IS NULL)),
    CHECK (state NOT IN ('reserved','returned','auctioned') OR kind='found'),
    CHECK (state NOT IN ('published','reserved','returned','auctioned') OR
           (moderator_id IS NOT NULL AND moderated_at IS NOT NULL))
);
CREATE TABLE lf_listing_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id bigint NOT NULL REFERENCES lf_listings ON DELETE CASCADE,
    object_key varchar(240) NOT NULL UNIQUE,
    media_type varchar(20) NOT NULL CHECK (media_type IN ('image/jpeg','image/png','image/webp')),
    size_bytes integer NOT NULL CHECK (size_bytes BETWEEN 1 AND 5242880),
    position smallint NOT NULL CHECK (position BETWEEN 1 AND 5),
    UNIQUE (listing_id,position)
);
CREATE TABLE lf_private_attributes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id bigint NOT NULL REFERENCES lf_listings ON DELETE CASCADE,
    name varchar(80) NOT NULL,
    value text NOT NULL,
    UNIQUE (listing_id,name)
);
CREATE TABLE lf_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id bigint NOT NULL REFERENCES lf_listings,
    claimant_id bigint NOT NULL REFERENCES lf_users,
    evidence text NOT NULL CHECK (length(trim(evidence))>0),
    state varchar(12) NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','accepted','rejected','cancelled','fulfilled')),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (id,listing_id)
);
CREATE TABLE lf_conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id bigint NOT NULL UNIQUE REFERENCES lf_claims,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE lf_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL REFERENCES lf_conversations,
    sender_id bigint NOT NULL REFERENCES lf_users,
    body text NOT NULL CHECK (length(trim(body)) BETWEEN 1 AND 4000),
    sent_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE lf_transfers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id bigint NOT NULL UNIQUE REFERENCES lf_claims,
    finder_confirmed_at timestamptz,
    owner_confirmed_at timestamptz,
    moderator_id bigint REFERENCES lf_users,
    override_reason text,
    completed_at timestamptz,
    CHECK ((moderator_id IS NULL)=(override_reason IS NULL)),
    CHECK (override_reason IS NULL OR length(trim(override_reason))>0),
    CHECK ((completed_at IS NOT NULL)=((finder_confirmed_at IS NOT NULL AND owner_confirmed_at IS NOT NULL) OR moderator_id IS NOT NULL))
);
CREATE TABLE lf_complaints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id bigint NOT NULL REFERENCES lf_users,
    listing_id bigint REFERENCES lf_listings,
    reported_user_id bigint REFERENCES lf_users,
    reason text NOT NULL CHECK (length(trim(reason))>0),
    state varchar(12) NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','resolved','rejected')),
    moderator_id bigint REFERENCES lf_users,
    resolution text,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK (num_nonnulls(listing_id,reported_user_id)=1),
    CHECK (state='pending' OR (moderator_id IS NOT NULL AND resolution IS NOT NULL AND length(trim(resolution))>0))
);
CREATE TABLE lf_auction_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id bigint NOT NULL REFERENCES lf_listings,
    applicant_id bigint NOT NULL REFERENCES lf_users,
    basis varchar(20) NOT NULL CHECK (basis IN ('six_months','other_title')),
    evidence_object_key varchar(240) NOT NULL,
    state varchar(12) NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','approved','rejected')),
    moderator_id bigint REFERENCES lf_users,
    reviewed_at timestamptz,
    reason text,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (id,listing_id,applicant_id),
    CHECK (state='pending' OR (moderator_id IS NOT NULL AND reviewed_at IS NOT NULL)),
    CHECK (state<>'rejected' OR (reason IS NOT NULL AND length(trim(reason))>0))
);
CREATE TABLE lf_auctions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id bigint NOT NULL REFERENCES lf_listings,
    seller_id bigint NOT NULL REFERENCES lf_users,
    permission_id bigint NOT NULL,
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    start_price numeric(12,2) NOT NULL CHECK (start_price>0),
    bid_step numeric(12,2) NOT NULL CHECK (bid_step>0),
    state varchar(12) NOT NULL DEFAULT 'scheduled' CHECK (state IN ('scheduled','active','suspended','finished','cancelled')),
    winner_bid_id bigint,
    closed_at timestamptz,
    FOREIGN KEY (permission_id,listing_id,seller_id) REFERENCES lf_auction_permissions(id,listing_id,applicant_id),
    CHECK (ends_at>starts_at),
    CHECK (winner_bid_id IS NULL OR state='finished'),
    CHECK ((state IN ('finished','cancelled'))=(closed_at IS NOT NULL))
);
CREATE TABLE lf_bids (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id bigint NOT NULL REFERENCES lf_auctions,
    bidder_id bigint NOT NULL REFERENCES lf_users,
    request_key uuid NOT NULL UNIQUE,
    amount numeric(12,2) NOT NULL CHECK (amount>0),
    placed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (auction_id,id)
);
ALTER TABLE lf_auctions ADD CONSTRAINT lf_winner_same_auction
    FOREIGN KEY (id,winner_bid_id) REFERENCES lf_bids(auction_id,id) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE lf_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES lf_users,
    kind varchar(40) NOT NULL,
    body text NOT NULL,
    read_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE lf_outbox_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind varchar(40) NOT NULL,
    aggregate_id bigint NOT NULL,
    payload jsonb NOT NULL CHECK (jsonb_typeof(payload)='object'),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts>=0),
    next_attempt_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    delivered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE lf_audit_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id bigint REFERENCES lf_users,
    action varchar(80) NOT NULL,
    entity_table varchar(80) NOT NULL,
    entity_id bigint NOT NULL,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
