spring.application.name=poteryashki
spring.main.web-application-type=none
spring.datasource.url=${DB_URL:jdbc:postgresql://pg:5432/studs?currentSchema=s465826}
spring.datasource.username=${DB_USER:s465826}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=1
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.naming.physical-strategy=ru.itmo.is.poteryashki.persistence.TableNamingStrategy
spring.jpa.properties.hibernate.lf_prefix=${DB_PREFIX:lf_}
app.table-prefix=${DB_PREFIX:lf_}
app.demo=${APP_DEMO:false}
logging.level.org.hibernate=warn
